<?php
// Include the configuration file, which contains database connection details.
require_once __DIR__ . '/api_config.php';

// Define a class named API to encapsulate API functionality.
class API {
    // Define a method for selecting data from the database.
    function select(){
        // Create a new database connection using the Connect class (assumed to be defined elsewhere).
        $db = new Connect;
        
        // Initialize an empty array to store user data.
        $users = array();
        
        // Prepare and execute a SQL query to select user data from the database.
        $data = $db->prepare('SELECT user_id, username, email, registration_date FROM sc_users ORDER BY user_id');
        $data->execute();
        
        // Fetch and organize the selected data into an associative array.
        while($OutputData = $data->fetch(PDO::FETCH_ASSOC)){
            $users[$OutputData['user_id']] = array(
                'user_id' => $OutputData['user_id'],
                'username' => $OutputData['username'],
                'email' => $OutputData['email'],
                'registration_date' => $OutputData['registration_date']
            );
        }
        
        // Return the selected user data as a JSON-encoded string.
        return json_encode($users);
    }
}

// Create an instance of the API class.
$API = new API;

// Set the response content type to JSON.
header('Content-Type: application/json');

// Output the JSON response generated by the select() method of the API instance.
echo $API->select();

//http://localhost/tickettoride-web/ticket-to-ride/API/api.php
?>